export const contactForm = {
  title: 'Counselling Call Enquiry',
  confirmationType: 'message' as const,
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: "🎉 You're booked!",
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Our counsellor will WhatsApp you within 1 working day. You can also reach us directly at +91 99460 33355.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  fields: [
    {
      name: 'fullName',
      label: 'Full Name',
      required: true,
      blockType: 'text' as const,
      width: 100,
    },
    {
      name: 'phone',
      label: 'Phone / WhatsApp',
      required: true,
      blockType: 'text' as const,
      width: 100,
    },
    {
      name: 'interestedCourse',
      label: 'Interested Course',
      required: true,
      blockType: 'select' as const,
      options: [
        { label: 'Hospital Administration', value: 'hospital-administration' },
        { label: 'Logistics & Supply Chain', value: 'logistics-supply-chain' },
        { label: 'Oil & Gas', value: 'oil-gas' },
        { label: 'HR Management', value: 'hr-management' },
        { label: 'Not sure — help me decide', value: 'not-sure' },
      ],
      width: 100,
    },
    {
      name: 'qualification',
      label: 'Qualification',
      required: true,
      blockType: 'select' as const,
      options: [
        { label: '12th', value: '12th' },
        { label: 'Diploma / ITI', value: 'diploma-iti' },
        { label: 'Degree', value: 'degree' },
        { label: 'Postgraduate', value: 'postgraduate' },
        { label: 'Working Professional', value: 'working-professional' },
      ],
      width: 100,
    },
    {
      name: 'message',
      label: 'Any specific question? (Optional)',
      required: false,
      blockType: 'textarea' as const,
      width: 100,
    },
  ],
  submitButtonLabel: '📞 Get My Free Call →',
}
