/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    programs: Program;
    testimonials: Testimonial;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Choose a Skillversity page template. Use Custom only for block-builder pages.
   */
  template:
    | 'home'
    | 'about'
    | 'admissions'
    | 'contact'
    | 'placements'
    | 'mentors'
    | 'campus-life'
    | 'skillfolio'
    | 'privacy'
    | 'custom';
  /**
   * Editor-friendly fields rendered by the branded Skillversity templates.
   */
  skillversity?: {
    hero?: {
      eyebrow?: string | null;
      title?: string | null;
      highlight?: string | null;
      description?: string | null;
      theme?: ('light' | 'cool' | 'warm' | 'dark') | null;
      primaryCtaLabel?: string | null;
      primaryCtaUrl?: string | null;
      secondaryCtaLabel?: string | null;
      secondaryCtaUrl?: string | null;
    };
    stats?:
      | {
          value: string;
          label: string;
          description?: string | null;
          color?: string | null;
          id?: string | null;
        }[]
      | null;
    featureCards?:
      | {
          icon?: string | null;
          title: string;
          description: string;
          color?: string | null;
          id?: string | null;
        }[]
      | null;
    contentSections?:
      | {
          eyebrow?: string | null;
          title: string;
          description?: string | null;
          items?:
            | {
                title: string;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  /**
   * Used only when Template is set to Custom Blocks Page.
   */
  layout?:
    | (
        | HeroCollageBlock
        | CompaniesMarqueeBlock
        | StatsRowBlock
        | ProgramsGridBlock
        | RealityCheckBlock
        | CertificationsGridBlock
        | TestimonialsGridBlock
        | MentorsGalleryBlock
        | PlacementsGalleryBlock
        | CampusLifeBlock
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Display label on blog card, e.g. "Logistics", "Healthcare"
   */
  categoryLabel?: string | null;
  /**
   * CSS color for the category badge, e.g. "#1A3DB8"
   */
  categoryColor?: string | null;
  /**
   * e.g. "8 min read"
   */
  readTime?: string | null;
  /**
   * CSS gradient for blog card thumbnail, e.g. "linear-gradient(135deg,#0A007A,#1A3DB8)"
   */
  cardGradient?: string | null;
  /**
   * Emoji icon for blog card, e.g. "📦"
   */
  cardIcon?: string | null;
  /**
   * Short description shown on blog listing cards
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in one sentence. This is read aloud by screen readers and used by search engines and AI crawlers. Avoid generic words like "image" or "photo" on their own.
   */
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins manage users and settings. Editors manage website content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCollageBlock".
 */
export interface HeroCollageBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  headline: string;
  highlight?: string | null;
  description?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaUrl?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaUrl?: string | null;
  whatsappLabel?: string | null;
  whatsappUrl?: string | null;
  rating?: string | null;
  /**
   * Show the 4 mini stat boxes below the rating (uses Site Settings stats).
   */
  showStats?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroCollage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompaniesMarqueeBlock".
 */
export interface CompaniesMarqueeBlock {
  hidden?: boolean | null;
  /**
   * Caption shown above the scrolling row.
   */
  title?: string | null;
  /**
   * Pull company names from Site Settings → Hiring Partner Companies. Uncheck to override with the list below.
   */
  useSiteSettings?: boolean | null;
  companies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'companiesMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock".
 */
export interface StatsRowBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  /**
   * Use the global Site Settings stats, or define custom stats for this block instance.
   */
  source?: ('siteSettings' | 'custom') | null;
  stats?:
    | {
        /**
         * e.g. "1845+"
         */
        value: string;
        /**
         * e.g. "Placements in 2025"
         */
        label: string;
        /**
         * Optional secondary line under the label
         */
        description?: string | null;
        color?: ('pink' | 'blue' | 'orange' | 'cyan' | 'yellow') | null;
        id?: string | null;
      }[]
    | null;
  background?: ('white' | 'cream') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsGridBlock".
 */
export interface ProgramsGridBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  columns?: ('2' | '4') | null;
  background?: ('gridPaper' | 'white' | 'cream') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'programsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealityCheckBlock".
 */
export interface RealityCheckBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  headline: string;
  highlight?: string | null;
  description?: string | null;
  painPoints?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  cardTape?: string | null;
  cardHeading?: string | null;
  cardBody?: string | null;
  cardItems?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'realityCheck';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsGridBlock".
 */
export interface CertificationsGridBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  theme?: ('dark' | 'light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'certificationsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsGridBlock".
 */
export interface TestimonialsGridBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  /**
   * Only show testimonials marked Featured in the Testimonials collection.
   */
  featuredOnly?: boolean | null;
  maxCount?: number | null;
  background?: ('white' | 'cream') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MentorsGalleryBlock".
 */
export interface MentorsGalleryBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  background?: ('cream' | 'white') | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mentorsGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlacementsGalleryBlock".
 */
export interface PlacementsGalleryBlock {
  hidden?: boolean | null;
  bigNumber?: string | null;
  heading?: string | null;
  description?: string | null;
  pills?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel?: string | null;
  primaryCtaUrl?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaUrl?: string | null;
  background?: ('white' | 'cream') | null;
  galleryCaption?: string | null;
  statCardNum?: string | null;
  statCardLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'placementsGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CampusLifeBlock".
 */
export interface CampusLifeBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  /**
   * Up to 7 items rendered in a bento grid. Fill in label + image. The first 7 follow a fixed layout (large, wide, medium, tall, small, small, small).
   */
  items?:
    | {
        image?: (number | null) | Media;
        label: string;
        placeholderLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'campusLife';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  headline?: string | null;
  /**
   * Second line of headline, rendered in yellow
   */
  highlight?: string | null;
  description?: string | null;
  primaryLabel?: string | null;
  primaryUrl?: string | null;
  secondaryLabel?: string | null;
  secondaryUrl?: string | null;
  whatsappLabel?: string | null;
  whatsappUrl?: string | null;
  phoneDisplay?: string | null;
  phoneUrl?: string | null;
  email?: string | null;
  showForm?: boolean | null;
  /**
   * Legacy field. Prefer structured fields above.
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Legacy field, ignored by render. Prefer button label/url fields above.
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  hidden?: boolean | null;
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  hidden?: boolean | null;
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  hidden?: boolean | null;
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  /**
   * Optional rich text intro. Prefer the title/description fields above.
   */
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  hidden?: boolean | null;
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Skillversity career programs displayed on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  /**
   * e.g. "Hospital Administration"
   */
  title: string;
  /**
   * e.g. "hospital-administration" — used in /programs/{slug}
   */
  slug: string;
  /**
   * Short tag shown on card, e.g. "Healthcare", "Global Trade"
   */
  tag: string;
  /**
   * CSS color or gradient, e.g. "#00B6E8"
   */
  tagColor: string;
  /**
   * Primary accent color for this program, e.g. "#00B6E8"
   */
  accentColor: string;
  /**
   * Fallback gradient for the card header when no image is uploaded. e.g. "linear-gradient(135deg,#E0F7FD,#FFE4ED)"
   */
  cardGradient: string;
  /**
   * Optional. Replaces the gradient header on program cards.
   */
  cardImage?: (number | null) | Media;
  /**
   * Shown on program cards. 1-2 sentences max.
   */
  shortDescription: string;
  /**
   * e.g. "10 / 12 months"
   */
  duration: string;
  /**
   * e.g. "12th, Degree, Diploma"
   */
  eligibility: string;
  /**
   * Lower number = shown first. e.g. 1, 2, 3, 4
   */
  sortOrder: number;
  status: 'active' | 'coming-soon' | 'inactive';
  /**
   * Main headline on the program detail page
   */
  heroHeadline?: string | null;
  /**
   * Description text below the hero headline
   */
  heroDescription?: string | null;
  /**
   * Optional CSS gradient for the detail-page hero (used when no Hero Image is set)
   */
  heroGradient?: string | null;
  /**
   * Full-bleed background photo behind the hero headline. Wide images work best (1600×900+). Falls back to the gradient when empty.
   */
  heroImage?: (number | null) | Media;
  /**
   * Shown in the overview strip, e.g. "India + GCC"
   */
  market?: string | null;
  /**
   * Short label shown in the overview strip, e.g. "Qualifi UK"
   */
  certificationLabel?: string | null;
  statBoxes?:
    | {
        value: string;
        label: string;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  overview?: {
    heading?: string | null;
    subhead?: string | null;
    body?: string | null;
    calloutTitle?: string | null;
    calloutBody?: string | null;
  };
  /**
   * Key features shown on the program detail page
   */
  highlights?:
    | {
        /**
         * Emoji icon, e.g. "🏥"
         */
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  modules?:
    | {
        title: string;
        topics?:
          | {
              topic: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Job roles graduates can pursue
   */
  careerRoles?:
    | {
        /**
         * e.g. "Front Office Executive"
         */
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Cards shown in the "Where graduates work" section. Each card supports an optional cover image.
   */
  careerPaths?:
    | {
        image?: (number | null) | Media;
        /**
         * e.g. "🏥"
         */
        icon?: string | null;
        title: string;
        /**
         * CSS color for the title, e.g. "var(--brand-blue)" or "#00B6E8"
         */
        color?: string | null;
        employers?: string | null;
        roles?:
          | {
              role: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Original JSON-based field, kept as a backup after migration to the structured Career Pathways array above. Edits here are ignored by the render.
   */
  careerPathsLegacy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * e.g. "₹15K–25K/month (India) · AED 2,500–5,000/month (Gulf)"
   */
  salaryRange?: string | null;
  salary?: {
    india?: string | null;
    indiaDesc?: string | null;
    gulf?: string | null;
    gulfDesc?: string | null;
  };
  certifications?:
    | {
        /**
         * e.g. "Qualifi UK"
         */
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional testimonials to show on this program page.
   */
  featuredTestimonials?: (number | Testimonial)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage student testimonials displayed on the homepage and other pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  studentName: string;
  /**
   * e.g. "NL" for Nikitha Lal — shown in avatar circle
   */
  initials: string;
  /**
   * e.g. "Sales Executive"
   */
  role: string;
  /**
   * e.g. "JFS Logistics"
   */
  company: string;
  /**
   * The student's actual testimonial text
   */
  quote: string;
  /**
   * CSS color for the avatar circle, e.g. "var(--brand-pink)"
   */
  accentColor: string;
  /**
   * Which program this student graduated from
   */
  program?: (number | null) | Program;
  /**
   * Optional: student photo for testimonial card
   */
  photo?: (number | null) | Media;
  /**
   * Check to show this testimonial on the homepage
   */
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  template?: T;
  skillversity?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
              theme?: T;
              primaryCtaLabel?: T;
              primaryCtaUrl?: T;
              secondaryCtaLabel?: T;
              secondaryCtaUrl?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              description?: T;
              color?: T;
              id?: T;
            };
        featureCards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              color?: T;
              id?: T;
            };
        contentSections?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
            };
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        heroCollage?: T | HeroCollageBlockSelect<T>;
        companiesMarquee?: T | CompaniesMarqueeBlockSelect<T>;
        statsRow?: T | StatsRowBlockSelect<T>;
        programsGrid?: T | ProgramsGridBlockSelect<T>;
        realityCheck?: T | RealityCheckBlockSelect<T>;
        certificationsGrid?: T | CertificationsGridBlockSelect<T>;
        testimonialsGrid?: T | TestimonialsGridBlockSelect<T>;
        mentorsGallery?: T | MentorsGalleryBlockSelect<T>;
        placementsGallery?: T | PlacementsGalleryBlockSelect<T>;
        campusLife?: T | CampusLifeBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCollageBlock_select".
 */
export interface HeroCollageBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  headline?: T;
  highlight?: T;
  description?: T;
  primaryCtaLabel?: T;
  primaryCtaUrl?: T;
  secondaryCtaLabel?: T;
  secondaryCtaUrl?: T;
  whatsappLabel?: T;
  whatsappUrl?: T;
  rating?: T;
  showStats?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompaniesMarqueeBlock_select".
 */
export interface CompaniesMarqueeBlockSelect<T extends boolean = true> {
  hidden?: T;
  title?: T;
  useSiteSettings?: T;
  companies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsRowBlock_select".
 */
export interface StatsRowBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  source?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsGridBlock_select".
 */
export interface ProgramsGridBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  columns?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealityCheckBlock_select".
 */
export interface RealityCheckBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  headline?: T;
  highlight?: T;
  description?: T;
  painPoints?:
    | T
    | {
        item?: T;
        id?: T;
      };
  cardTape?: T;
  cardHeading?: T;
  cardBody?: T;
  cardItems?:
    | T
    | {
        item?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsGridBlock_select".
 */
export interface CertificationsGridBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsGridBlock_select".
 */
export interface TestimonialsGridBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  featuredOnly?: T;
  maxCount?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MentorsGalleryBlock_select".
 */
export interface MentorsGalleryBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  background?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlacementsGalleryBlock_select".
 */
export interface PlacementsGalleryBlockSelect<T extends boolean = true> {
  hidden?: T;
  bigNumber?: T;
  heading?: T;
  description?: T;
  pills?:
    | T
    | {
        label?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaUrl?: T;
  secondaryCtaLabel?: T;
  secondaryCtaUrl?: T;
  background?: T;
  galleryCaption?: T;
  statCardNum?: T;
  statCardLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CampusLifeBlock_select".
 */
export interface CampusLifeBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  items?:
    | T
    | {
        image?: T;
        label?: T;
        placeholderLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  headline?: T;
  highlight?: T;
  description?: T;
  primaryLabel?: T;
  primaryUrl?: T;
  secondaryLabel?: T;
  secondaryUrl?: T;
  whatsappLabel?: T;
  whatsappUrl?: T;
  phoneDisplay?: T;
  phoneUrl?: T;
  email?: T;
  showForm?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  hidden?: T;
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  hidden?: T;
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  hidden?: T;
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  categoryLabel?: T;
  categoryColor?: T;
  readTime?: T;
  cardGradient?: T;
  cardIcon?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tag?: T;
  tagColor?: T;
  accentColor?: T;
  cardGradient?: T;
  cardImage?: T;
  shortDescription?: T;
  duration?: T;
  eligibility?: T;
  sortOrder?: T;
  status?: T;
  heroHeadline?: T;
  heroDescription?: T;
  heroGradient?: T;
  heroImage?: T;
  market?: T;
  certificationLabel?: T;
  statBoxes?:
    | T
    | {
        value?: T;
        label?: T;
        color?: T;
        id?: T;
      };
  overview?:
    | T
    | {
        heading?: T;
        subhead?: T;
        body?: T;
        calloutTitle?: T;
        calloutBody?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  modules?:
    | T
    | {
        title?: T;
        topics?:
          | T
          | {
              topic?: T;
              id?: T;
            };
        id?: T;
      };
  careerRoles?:
    | T
    | {
        role?: T;
        id?: T;
      };
  careerPaths?:
    | T
    | {
        image?: T;
        icon?: T;
        title?: T;
        color?: T;
        employers?: T;
        roles?:
          | T
          | {
              role?: T;
              id?: T;
            };
        id?: T;
      };
  careerPathsLegacy?: T;
  salaryRange?: T;
  salary?:
    | T
    | {
        india?: T;
        indiaDesc?: T;
        gulf?: T;
        gulfDesc?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  featuredTestimonials?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  studentName?: T;
  initials?: T;
  role?: T;
  company?: T;
  quote?: T;
  accentColor?: T;
  program?: T;
  photo?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage homepage stats, hiring partners, and certifications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  stats?: {
    /**
     * e.g. "10141" — will show as "10141+"
     */
    placements?: string | null;
    placementsLabel?: string | null;
    hiringPartners?: string | null;
    hiringPartnersLabel?: string | null;
    mentors?: string | null;
    mentorsLabel?: string | null;
    mentorshipYears?: string | null;
    mentorshipLabel?: string | null;
  };
  /**
   * Powers the AggregateRating schema on the organization JSON-LD. Surfaces as star ratings in Google search results.
   */
  rating?: {
    /**
     * e.g. "4.8" — must be between 1 and 5
     */
    value?: string | null;
    /**
     * Total number of reviews backing the rating, e.g. "600"
     */
    count?: string | null;
  };
  /**
   * Companies shown in the scrolling marquee. Add/remove/reorder as needed.
   */
  hiringCompanies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        /**
         * Emoji icon, e.g. "🎓"
         */
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mentor avatars rendered on the /mentors page. Leave image empty to show a branded placeholder.
   */
  mentorsGallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Shown inside the avatar placeholder, e.g. "Dr Rajesh"
         */
        firstName?: string | null;
        /**
         * Shown below the avatar, e.g. "Dr Rajesh Menon"
         */
        fullName: string;
        /**
         * e.g. "Hospital Admin · 28 yrs · Aster Group"
         */
        credential?: string | null;
        roleType: 'mentor' | 'hod';
        id?: string | null;
      }[]
    | null;
  /**
   * Student alumni photos rendered on the /placements page next to the 1845+ stats card.
   */
  placementsGallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Shown inside the placeholder, e.g. "Nikitha"
         */
        firstName?: string | null;
        /**
         * Bottom strip, e.g. "Nikitha · JFS Logistics"
         */
        caption: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Up to 4 image slots shown beside the hero headline. Leave empty to show the branded placeholder.
   */
  heroCollage?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        badge?: string | null;
        overlay?: string | null;
        placeholderLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Founder & board of directors shown on the /about page. Upload a photo for each; leave a photo empty to show a branded placeholder.
   */
  leadership?:
    | {
        image?: (number | null) | Media;
        /**
         * e.g. "Mr. Ratheesh Ravi"
         */
        name: string;
        /**
         * e.g. "Founder MD"
         */
        role: string;
        /**
         * Ring colour around the photo
         */
        accent?: ('pink' | 'blue' | 'orange') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Photos shown on the /about page. Leave any empty to show a branded placeholder.
   */
  aboutPhotos?: {
    campusExterior?: (number | null) | Media;
    connectRoom?: (number | null) | Media;
    coreValuesWall?: (number | null) | Media;
    purposePlaque?: (number | null) | Media;
    classroomInterior?: (number | null) | Media;
  };
  heroHeadline?: string | null;
  heroHighlight?: string | null;
  heroDescription?: string | null;
  commonCta?: {
    primaryLabel?: string | null;
    primaryUrl?: string | null;
    secondaryLabel?: string | null;
    secondaryUrl?: string | null;
  };
  /**
   * The form rendered by Skillversity lead forms across the frontend.
   */
  leadForm?: (number | null) | Form;
  contact?: {
    /**
     * Display format, e.g. "+91 99460 33355"
     */
    phone?: string | null;
    /**
     * tel: link for click-to-call
     */
    phoneLink?: string | null;
    email?: string | null;
    /**
     * Number only (no +), used in wa.me link
     */
    whatsapp?: string | null;
    website?: string | null;
    address?: string | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  footerTagline?: string | null;
  analytics?: {
    /**
     * Overrides NEXT_PUBLIC_GA_ID when set.
     */
    googleAnalyticsId?: string | null;
    /**
     * Overrides NEXT_PUBLIC_META_PIXEL_ID when set.
     */
    metaPixelId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        placements?: T;
        placementsLabel?: T;
        hiringPartners?: T;
        hiringPartnersLabel?: T;
        mentors?: T;
        mentorsLabel?: T;
        mentorshipYears?: T;
        mentorshipLabel?: T;
      };
  rating?:
    | T
    | {
        value?: T;
        count?: T;
      };
  hiringCompanies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  mentorsGallery?:
    | T
    | {
        image?: T;
        firstName?: T;
        fullName?: T;
        credential?: T;
        roleType?: T;
        id?: T;
      };
  placementsGallery?:
    | T
    | {
        image?: T;
        firstName?: T;
        caption?: T;
        id?: T;
      };
  heroCollage?:
    | T
    | {
        image?: T;
        caption?: T;
        badge?: T;
        overlay?: T;
        placeholderLabel?: T;
        id?: T;
      };
  leadership?:
    | T
    | {
        image?: T;
        name?: T;
        role?: T;
        accent?: T;
        id?: T;
      };
  aboutPhotos?:
    | T
    | {
        campusExterior?: T;
        connectRoom?: T;
        coreValuesWall?: T;
        purposePlaque?: T;
        classroomInterior?: T;
      };
  heroHeadline?: T;
  heroHighlight?: T;
  heroDescription?: T;
  commonCta?:
    | T
    | {
        primaryLabel?: T;
        primaryUrl?: T;
        secondaryLabel?: T;
        secondaryUrl?: T;
      };
  leadForm?: T;
  contact?:
    | T
    | {
        phone?: T;
        phoneLink?: T;
        email?: T;
        whatsapp?: T;
        website?: T;
        address?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        linkedin?: T;
        youtube?: T;
      };
  footerTagline?: T;
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        metaPixelId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}